#!/bin/sh
clear
echo "



"
echo $PWD


NAME='simplenotes'
echo $NAME
echo "====================== nTex to LaTex   ===================="
java -jar nTexProject-1.1.jar -name $NAME

echo "====================== LaTex to PDF 1 ====================="
echo $NAME'.tex'
TEXNAME=$NAME'.tex'

pdflatex $TEXNAME
echo "====================== LaTex to PDF 2 ====================="
pdflatex $TEXNAME

echo "====================== Done ==============================="

PDFNAME=$NAME'.pdf'
okular $PDFNAME
