#!/bin/bash
clear
echo "



"
# @author Jaroslav Vitku
echo $PWD

# set the actual version of project here
VERSION="1.0"
APP="ntex-"$VERSION".jar"

NAME='notes'
echo $NAME
echo "====================== nTex to LaTex   ===================="
java -jar $APP -name $NAME

echo "====================== LaTex to PDF 1 ====================="
echo $NAME'.tex'
TEXNAME=$NAME'.tex'

pdflatex $TEXNAME
echo "====================== LaTex to PDF 2 ====================="
pdflatex $TEXNAME

echo "====================== Done ==============================="

PDFNAME=$NAME'.pdf'

MAC="darwin10.0"
ML="darwin12"
LINUX="linux-gnu"

if [ "$OSTYPE" = "$MAC" ]; then
    echo "Openning pdf under Mac OS X.."
    open -a Preview $PDFNAME
elif [ "$OSTYPE" = "$LINUX" ]; then
    echo "Openning pdf under Linux.."
    okular $PDFNAME
elif [ "$OSTYPE" = "$ML" ]; then
    echo "Openning pdf under Mac OS X ML"
    open -a preview $PDFNAME
else
    echo "Unknown type of OS: -" $OSTYPE "- ..openning nothin'.."
fi

