#!/bin/sh
clear
echo "



"
echo $PWD

# set the actual version of project !!!!
VERSION="2.0"
APP="ntexproject-"$VERSION".jar"

NAME='notes'
echo $NAME
echo "====================== nTex to LaTex   ===================="
java -jar $APP -name $NAME

echo "====================== LaTex to PDF 1 ====================="
echo $NAME'.tex'
TEXNAME=$NAME'.tex'

pdflatex $TEXNAME
echo "====================== LaTex to PDF 2 ====================="
pdflatex $TEXNAME

echo "====================== Done ==============================="

PDFNAME=$NAME'.pdf'

MAC="darwin10.0"
LINUX="linux-gnu"

if [ "$OSTYPE" = "$MAC" ]; then
    echo "Openning pdf under Mac OS X.."
    open -a Preview $PDFNAME
elif [ "$OSTYPE" = "$LINUX" ]; then
    echo "Openning pdf under Linux.."
    okular $PDFNAME
else
    echo "Unknown type of OS: -" $OSTYPE "- ..openning nothin'.."
fi

