#!/bin/sh
clear
echo "



"
echo $PWD

# set the actual version of project !!!!
VERSION="2.0"
APP="ntexproject-"$VERSION".jar"
MAC=0

NAME='notes'
echo $NAME
echo "====================== nTex to LaTex   ===================="
java -jar $APP -name $NAME

echo "====================== LaTex to PDF 1 ====================="
echo $NAME'.tex'
TEXNAME=$NAME'.tex'

pdflatex $TEXNAME
echo "====================== LaTex to PDF 2 ====================="
pdflatex $TEXNAME

echo "====================== Done ==============================="

PDFNAME=$NAME'.pdf'

if [ "$MAC" = 0 ]; then
    okular $PDFNAME
else
    open -a Preview $PDFNAME
fi
