#!/bin/sh
#clear
#echo ""

# This thing will deploy the files necessary to initialize the ntex project in the current folder!
# made by Jaroslav Vitku


# this is where I am (and all things to copy)
BASEDIR=$(dirname $0)
#echo $BASEDIR

# this is the destination folder (where to copy)
#echo $PWD

#NAME='notes'
#echo $NAME


# print intro
pi(){
	echo " "
	echo "====================== Info ===================="
	echo "This script deplys nTex files into an actual folder, can also init the ntex file with template"
	echo " "
}

# notes
pn(){
	echo "note: now you can:
	-edit the 'notes.ntex' file and/or
	-run the ./compile script in order to generate LaTeX and PDF files"
}

# print usage
pu()
{
	echo " "
	echo "====================== Usage ===================="
	echo 	"Type 'ntex init' to just copy files"
	echo	"Type 'ntex generate' to copy and generate template file too"
	echo 	"Type 'ntex help' for information how to use this"
	echo "================================================="
	echo " "
}

# copy files
deploy()
{
    echo ""
	echo "====================== Deploying files to the place ===================="
	echo "Intalling application, copying files from:
	$BASEDIR
	to:
	$PWD"

	cp $BASEDIR$REL$APP $PWD
	cp $BASEDIR'/IEEEtrancz.cls' $PWD
	cp $BASEDIR'/template.tex' $PWD
	cp $BASEDIR'/compile' $PWD

	echo "..done"
	echo " "
}

# init file
init()
{
	echo "====================== Generating notes.ntex file  ====================="
	java -jar $APP -template y
	echo "..done"
	echo " "
}

# init file with short template
init2()
{
	echo "====================== Generating notes.ntex file  ====================="
	java -jar $APP -simpletemplate y
	echo "..done"
	echo " "
}

ph()
{
	echo "============================== ntex help  =============================="
	java -jar $APP -help y
}

ARGC=1
INIT="init"
TEMP="generate"
TEMP2="gen"
HELP="help"

# set the actual version of project !!!!
VERSION="2.0"
APP="ntexproject-"$VERSION".jar"
echo "\nProject name: "$APP

REL="/../build/install/ntexproject/lib/"

if [ "$#" -eq "$ARGC" ]; then
	if [ "$1" = "$INIT" ]; then
		deploy
		pn
	# make template
	elif [ "$1" = "$TEMP" ]; then
		deploy
		init
		#pn
	# make short template
	elif [ "$1" = "$TEMP2" ]; then
    	deploy
    	init2
    	#pn
	elif [ "$1" = "$HELP" ]; then
		deploy
		ph
	else
		pu
	fi
else
	pu
fi





