#!/bin/sh
# clear
#
# Ntex is a tool used for creating fast notes in LaTeX. 
# Application simplifies the most used LaTeX commands such as:
#	-bulleted lists
#	-citations
#	-figures
# ..while still supporting the rest of LaTeX original commands.
# Used can write fast and distract-free, yet still well-formatted documents.
#
# See README
# @author Jaroslav Vitku

# this is where I am (and all things to be copied)
BASEDIR=$(dirname $0)

# this is the destination folder (where to copy things)
# echo $PWD

# print intro
pi(){
	echo " "
	echo "====================== Info ===================="
	echo "This script deplys nTex files into an actual folder, can also init the ntex file with template"
	echo " "
}

# notes
pn(){
	echo "note: now you can:
	-edit the 'notes.ntex' file and/or
	-run the ./compile script in order to generate LaTeX and PDF files"
}

# print usage
pu()
{
	echo " "
	echo "====================== Usage ===================="
	echo 	"Type 'ntex init'	-initialize ntex with smaller ntex file"
	echo 	"Type 'ntex initialize'	-initialize ntex with full ntex file (with more examples)"
	echo 	"Type 'ntex help'	-for information how to use ntex"
	echo "================================================="
	echo " "
	echo "..for more information see README"
	echo " "
}

# copy files
deploy()
{
    echo ""
	echo "====================== Deploying files to the place ===================="
	echo "Intalling application, copying files from:
	$BASEDIR
	to:
	$PWD"

	cp $BASEDIR$REL$APP $PWD
	cp $BASEDIR'/IEEEtrancz.cls' $PWD
	cp $BASEDIR'/template.tex' $PWD
	cp $BASEDIR'/compile' $PWD

	echo "..done"
	echo " "
}

# check if notes.ntex already exists, if yes, make back up
check()
{
	if [ -f 'notes.ntex' ];
	then
   		echo "File notes.ntex found, backing up.."
		echo " "
		cp notes.ntex notes.ntex.orig
	fi
}


# init file
init()
{
	echo "====================== Generating smaller notes.ntex file  ====================="
	java -jar $APP -simpletemplate y
	echo "..done"
	echo " "
}

# init file with short template
init2()
{
	echo "====================== Generating full notes.ntex file  ====================="
	java -jar $APP -template y
	echo "..done"
	echo " "
}

ph()
{
	echo "============================== ntex help  =============================="
	java -jar $APP -help y
}

ARGC=1
INIT="init"
INIT2="initialize"

HELP="help"

# set the actual version of project !!!!
VERSION="1.0"
APP="ntex-"$VERSION".jar"
echo "\nProject name: "$APP

REL="/../build/install/ntex/lib/"

if [ "$#" -eq "$ARGC" ]; then
	# make template
	if [ "$1" = "$INIT" ]; then
		deploy
		check
		init
		#pn
	# make short template
	elif [ "$1" = "$INIT2" ]; then
    	deploy
		check
    	init2
    	#pn
	elif [ "$1" = "$HELP" ]; then
		deploy
		ph
	else
		pu
	fi
else
	pu
fi





