#!/bin/sh
MAC="darwin10.0"
LINUX="linux-gnu"

echo "tady!."
echo $OSTYPE
echo "tady!."

if [ "$OSTYPE" = "$MAC" ]; then
    echo "Openning pdf under Mac OS X.."
    open -a Preview $PDFNAME
elif [ "$OSTYPE" = "$LINUX" ]; then
    echo "Openning pdf under Linux.."
    okular $PDFNAME
else
    echo $OSTYPE
    echo "Unknown type of OS: -" $OSTYPE "- ..openning nothin'.."
fi
